config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :stories do
    resources :chapters
    collection do
        get 'all'
        get 'newest'
    end
  end
  resources :chapters do
    member do
      post 'upvote'
    end
  end

  root 'stories#index'

  match '/signup', to: 'users#new', via: 'get'
  match '/join', to: 'users#new', via: 'get'
  match '/login',  to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friendships
    has_many :friends, through: :friendships
    has_many :votes, dependent: :destroy
    has_many :upvoted_chapters, through: :votes, source: :chapter
    has_many :chapters, dependent: :destroy
    has_many :stories, dependent: :destroy
    before_save { self.email = email.downcase }
    before_create :create_remember_token
    validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: true }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }
    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    def is_admin
        is_admin = false
    end

    private

        def create_remember_token
            self.remember_token = User.digest(User.new_remember_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        sign_in @user
        redirect_to @user, notice: 'You have signed up successfully.'

      else
        render :new    
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-md-5 col-xs-12">
        <div class="field">
            <%= f.text_field :name, placeholder: "Name" %>
        </div>
        <div class="field">
            <%= f.text_field :email, placeholder: "Email" %>
        </div>
        <div class="field">
            <%= f.password_field :password, placeholder: "Password" %>
        </div>
        <div class="actions pull-right">
            <%= f.submit params[:action] == 'new' ? "Join" : "Update" %>
        </div>
    </div>
<% end %>

app/views/users/_story.html.erb
<li>
  <span class="content"><%= story.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(story.created_at) %> ago.
  </span>
  <% if current_user?(story.user) %>
    <%= link_to "delete", story, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: story.content %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="pageContainer">
    <div class="container">
        <% if current_user == @user %>  
            <h1>Edit your profile</h1>
            <div class="userProfile">
                <%= gravatar_for @user %>
                <a href="http://gravatar.com/emails" class="btn btn-inverse userImageBtn">Update your avatar</a>
            </div>

            <%= render 'form' %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="pageContainer">
    <div class="container">    
        <ul class="simpleList">
            <% @users.each do |user| %>
                <li>
                    <%= link_to(user) do %>
                        <span><%= user.name %></span>
                        <% if current_user != user && signed_in? %>
                            <% if current_user.friendships.find_by_friend_id(user) %>
                                - <%= link_to "remove", friendship_path(current_user.friendships.find_by_friend_id(user)), :method => :delete %>
                            <% else %>
                                - <%= link_to "Add friend", friendships_path(:friend_id => user), :method => :post %>
                            <% end %>
                        <% end %>
                    <% end %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/users/new.html.erb
<div class="pageContainer">
    <div class="container">
        <h1>Join Story Wars</h1>
        <div class="col-md-7">
            <ul class="simpleList largeList marginBottom">
                <li>Write your own short stories</li>
                <li>Challenge your friends</li>
                <li>Continue on other authors stories</li>
                <li>Vote on how a story should continue</li>
            </ul>
        </div>
        <%= render 'form' %>

    </div>
</div>

app/views/users/show.html.erb
<div class="pageContainer">
    <div class="container">    
        <p id="notice"><%= notice %></p>
        
        <%# This should be moved to a model %>
        <% user_votes = 0 %>
        <% @user.stories.each do |story| %>
            <% story.chapters.each do |chapter| %>
                <% user_votes = user_votes + chapter.votes.count %>
            <% end %>
        <% end %>

        <% @user.chapters.each do |chapter| %>
            <% user_votes = user_votes + chapter.votes.count %>
        <% end %>
        
        <div class="userProfile borderTop">
            <% if signed_in? %>
                <div class="col-sm-4 col-xs-12 pull-right">
                    <div class="userButtons pull-right">
                        <% if current_user == @user %>  
                            <%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-inverse" %>
                            <%= link_to "Logout", logout_path, method: "delete", class: "btn marginLeft" %>
                        <% elsif current_user != @user && !current_user.friendships.find_by_friend_id(@user) %>
                            <%= link_to "Add friend", friendships_path(:friend_id => @user), :method => :post, class: "btn" %>
                        <% elsif current_user != @user && current_user.friendships.find_by_friend_id(@user) %>
                            <%= link_to "Remove friend", friendship_path(current_user.friendships.find_by_friend_id(@user)), :method => :delete, class: "btn btn-inverse" %>
                        <% end %>
                    </div>
                </div>
            <% end %>
            <div class="col-sm-8 col-xs-12">
                <%= gravatar_for @user %>
                <h1 class="userHeadline">
                    <%= @user.name %> (<%= user_votes %> p)
                </h1>
            </div>
        </div>


        <!-- 
        <% if @user.stories.any? %>
            <h3>Stories (<%= @user.stories.count %>)</h3>
            <ol>
                <%= render @user.stories %>
            </ol>
        <% end %> -->
        <% if @user.stories.any? %>
            <ul class="primaryList borderTop paddingTop marginBottom--4x">
                <h2 class="marginBottom">Stories</h2>
                <% @user.stories.each do |story| %>
                    <% votes = 0 %>
                    <% story.chapters.each do |chapter| %>
                        <% votes = votes + chapter.votes.count %>
                    <% end %>
                    <li>
                        <%= link_to(story, class: "primaryHeadline") do %>
                            <span><%= story.title %></span>
                            <div class="extraInfo">
                                <span><%= votes %> p</span>
                            </div>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
        <% if @user.chapters.any? %>
            <div class="pull-left col-xs-12 paddingTop borderTop marginBottom--4x">
                <h2>Chapters</h2>
                <ul>
                    <% @user.chapters.each do |chapter| %>
                        <li class="voteChapter-container">
                            <article class="voteChapter-content" data-readmore="Read more"><%= simple_format(chapter.body) %>
                                <%= link_to "Show story", story_path(chapter.story), :class => "secondaryLink" %>
                                <span class="pull-right"><%= chapter.votes.count %> p</span>
                            </article>
                        </li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        
        <% if @user.friends.any? || current_user == @user %>
            <div class="pull-left col-xs-12 paddingTop borderTop marginBottom">
                <h2>Friends</h2>
                <ul class="simpleList marginBottom">
                    <% @user.friends.each do |user| %>
                        <li>
                            <%= link_to(user, class: "primaryHeadline") do %>
                                <span><%= user.name %></span>
                            <% end %>
                            <% if current_user == @user %>
                                - <%= link_to "remove", friendship_path(current_user.friendships.find_by_friend_id(user)), :method => :delete %>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
                <%= link_to "Find friends", users_path %>
            </div>
        <% end %>

    </div>
</div>