config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :stories do
    resources :chapters
    collection do
        get 'all'
        get 'newest'
    end
  end
  resources :chapters do
    member do
      post 'upvote'
    end
  end

  root 'stories#index'

  match '/signup', to: 'users#new', via: 'get'
  match '/join', to: 'users#new', via: 'get'
  match '/login',  to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/story.rb
class Story < ActiveRecord::Base
    belongs_to :user
    has_many :chapters
    default_scope -> { order('created_at DESC') }
    validates :title, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 2000 }
    validates :user_id, presence: true

    def timeLeft
        if (self.created_at > 14.hour.ago)
            timeLeft = ((Time.parse(DateTime.now.to_s) - Time.parse(self.created_at.to_s))/3600) - ((Time.parse(DateTime.now.to_s) - Time.parse(self.created_at.to_s))/3600).floor
            timeLeft = (60 - (60 * timeLeft)).ceil


            # For the formated version that we don't right now
            #timeLeft = Time.now + timeLeft.minutes
            #timeLeft = timeLeft.strftime("%Y/%m/%d %H:%M:%S")
        else 
            timeLeft = false
        end
    end

    def self.most_voted
        Story.all.sort_by do |story|
            story.chapters.map do |chapter| 
                chapter.votes.count
            end.reduce(0, :-)
        end
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    # @stories = Story.all
    @stories = Story.most_voted
  end

  def all
    @all_stories = Story.most_voted
  end

  def newest
    @newest_stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
        @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :content, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
    <% if @story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

          <ul>
          <% @story.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>
  
    <div class="field">
        <%= f.text_field :title, placeholder: "Title of the story" %>
    </div>
    <div class="field">
        <%= f.text_area :content, placeholder: "Your story" %>
    </div>
    <div class="field">
        <input id="story_user_id" name="story[user_id]" type="hidden" value="<%= current_user.id %>">
    </div>

    <div class="actions pull-right">
        <%= f.submit %>
    </div>
<% end %>

app/views/stories/_story.html.erb
<li>
  <span class="content"><%= story.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(story.created_at) %> ago.
  </span>
</li>

app/views/stories/all.html.erb
<div class="pageContainer">
    <div class="container">
        <ul class="primaryList">
            <% @all_stories.each do |story| %>
                <% votes = 0 %>
                <% story.chapters.each do |chapter| %>
                    <% votes = votes + chapter.votes.count %>
                <% end %>
                <li>
                    <%= link_to(story, class: "primaryHeadline") do %>
                        <span><%= story.title %></span>
                        <div class="extraInfo">
                            <span><%= votes %> p</span>
                        </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
        <%-# link_to "Back to most popular", { :controller => "stories", :action => "index" }, :class => "pull-right marginTop marginBottom btn" -%>
    </div>
</div>

app/views/stories/edit.html.erb
<% if current_user.is_admin == true %>
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>
<% else %>
Not allowed to edit
<% end %>

app/views/stories/index.html.erb
<div class="pageContainer">
    <% if !signed_in? %>
        <div class="heroImg">
            <div class="container">
                <h1><span>Write your story</span>and challenge your friends into a writing match</h1>
                <div class="textCenter"><%= link_to "Join now", join_path, class: "btn btn-inverse marginBottom" %></div>
            </div>
        </div>
    <% end %>
    <div class="container">
        <ul class="primaryList">
            <% @stories.each_with_index do |story, index| %>
                <% if index > 7 %>
                    <% break %>
                <% end %>
                <% votes = 0 %>
                <% story.chapters.each do |chapter| %>
                    <% votes = votes + chapter.votes.count %>
                <% end %>
                <li>
                    <%= link_to(story, class: "primaryHeadline") do %>
                        <span><%= story.title %></span>
                        <div class="extraInfo">
                            <span><%= votes %> p</span>
                        </div>
                    <% end %>

                </li>
            <% end %>
        </ul>
        <%= link_to "Newest stories", { :controller => "stories", :action => "newest" }, :class => "pull-right marginTop marginBottom marginLeft btn" %>
        <%= link_to "All stories", { :controller => "stories", :action => "all" }, :class => "pull-right marginTop marginBottom btn" %>
    </div>
</div>

app/views/stories/new.html.erb
<% if signed_in? %>
    <div class="pageContainer">
        <div class="container">  
            <h1>New story</h1>

            <%= render 'form' %>
        </div>
    </div>
<% else %>
    <script type="text/javascript">
        window.location.href="/login"
    </script>
<% end %>

app/views/stories/newest.html.erb
<div class="pageContainer">
    <div class="container">
        <ul class="primaryList">
            <% @newest_stories.each_with_index do |story, index| %>
                <% if index > 7 %>
                    <% break %>
                <% end %>
                <% votes = 0 %>
                <% story.chapters.each do |chapter| %>
                    <% votes = votes + chapter.votes.count %>
                <% end %>
                <li>
                    <%= link_to(story, class: "primaryHeadline") do %>
                        <span><%= story.title %></span>
                        <div class="extraInfo">
                            <span><%= votes %> p</span>
                        </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
        <%-# link_to "Back to most popular", { :controller => "stories", :action => "index" }, :class => "pull-right marginTop marginBottom btn" -%>
    </div>
</div>

app/views/stories/show.html.erb
<%# This should be redone and should be moved to a model %>
<% if @story.created_at > 1.hour.ago %>
    <% round = 2 %>
    <% vote = false %>
<% elsif @story.created_at <= 1.hour.ago && @story.created_at > 2.hour.ago %>
    <% round = 2 %>
    <% vote = true %>
<% elsif @story.created_at < 2.hour.ago && @story.created_at > 3.hour.ago %>
    <% round = 3 %>
    <% vote = false %>
<% elsif @story.created_at < 3.hour.ago && @story.created_at > 4.hour.ago %>
    <% round = 3 %>
    <% vote = true %>
<% elsif @story.created_at < 4.hour.ago && @story.created_at > 5.hour.ago %>
    <% round = 4 %>
    <% vote = false %>
<% elsif @story.created_at < 5.hour.ago && @story.created_at > 6.hour.ago %>
    <% round = 4 %>
    <% vote = true %>
<% elsif @story.created_at < 6.hour.ago && @story.created_at > 7.hour.ago %>
    <% round = 5 %>
    <% vote = false %>
<% elsif @story.created_at < 7.hour.ago && @story.created_at > 8.hour.ago %>
    <% round = 5 %>
    <% vote = true %>
<% elsif @story.created_at < 8.hour.ago && @story.created_at > 9.hour.ago %>
    <% round = 6 %>
    <% vote = false %>
<% elsif @story.created_at < 9.hour.ago && @story.created_at > 10.hour.ago %>
    <% round = 6 %>
    <% vote = true %>
<% elsif @story.created_at < 10.hour.ago && @story.created_at > 11.hour.ago %>
    <% round = 7 %>
    <% vote = false %>
<% elsif @story.created_at < 11.hour.ago && @story.created_at > 12.hour.ago %>
    <% round = 7 %>
    <% vote = true %>
<% elsif @story.created_at < 12.hour.ago && @story.created_at > 13.hour.ago %>
    <% round = 8 %>
    <% vote = false %>
<% elsif @story.created_at < 13.hour.ago && @story.created_at > 14.hour.ago %>
    <% round = 8 %>
    <% vote = true %>
<% end %>
<% friends = [] %>
<div class="pageContainer whitePageContainer">
    <div class="container">  
        <p id="notice"><%= notice %></p>
        <h1 class="storyTitle"><%= @story.title %></h1>
        <h4 class="chapterInfo">
            Chapter 1 by <%= link_to(@story.user) do %>
                <%= @story.user.name %>
            <% end %>
        </h4>
        <article class="storyContent"><%= simple_format(@story.content) %></article>

        <% maxVotes = 0 %>
        <% chosenChapterRound = "" %>
        <% chosenChapters = [] %>
        <%-#= time_ago_in_words(@story.created_at) -%>
        <ul class="storyList">
            <% @story.chapters.each do |chapter| %>
                <% if signed_in? %>
                    <% user = User.find(chapter.user_id) %>
                    <% if current_user != user && current_user.friendships.find_by_friend_id(user) %>
                        <% if !friends.include?(user) %>
                            <% friends << user %>
                        <% end %>
                    <% end %>
                <% end %>
                <% if round.to_s != chapter.round %>
                    <% if chosenChapterRound != chapter.round %>
                        <% maxVotes = 0 %>
                    <% end %>

                    <% if chapter.votes.count > maxVotes %>
                        <% maxVotes = chapter.votes.count %>
                        <% chosenChapterRound = chapter.round %>
                        <% chosenChapters[round.to_i] = chapter %>
                    <% end %>
                <% end %>
            <% end %>
            <% chosenChapters.each do |chosenChapter| %>
                <% if chosenChapter.nil? == false %>
                    <li>
                        <h4 class="chapterInfo">Chapter <%= chosenChapter.round %> by <a href="/users/<%= chosenChapter.author %>"><%= chosenChapter.authorname %></a></h4>
                        <article class="storyContent"><%= simple_format(chosenChapter.body) %></article>
                    </li>
                <% end %>
            <% end %>
        </ul>
        
        <div class="col-xs-12 storySocial-info">
            <% if @story.created_at > 14.hour.ago %>
                <% if friends.any? %>
                    Challenge more friends:
                <% else %>
                    Challenge your friends:
                <% end %>
                <a target="_blank" href="https://www.facebook.com/sharer.php?u=href=<%= request.original_url %>" title="Share this story on Facebook"><i class="fa fa-facebook-square"></i></a>
                <a target="_blank" href="https://twitter.com/share?text=I%20would%20challenge%20you%20to%20a%20battle%20of%20wits,%20but%20I%20see%20you%20are%20unarmed!&url=<%= request.original_url %>&hashtags=shakespeare, storytelling, writing" title="Share this story on Twitter"><i class="fa fa-twitter-square"></i></a>
            <% else %>
                Share this masterpiece:
                <a target="_blank" href="https://www.facebook.com/sharer.php?u=href=<%= request.original_url %>" title="Share this story on Facebook"><i class="fa fa-facebook-square"></i></a>
                <a target="_blank" href="https://twitter.com/share?text=You%20must%20read%20this%20story!&url=<%= request.original_url %>" title="Share this story on Twitter"><i class="fa fa-twitter-square"></i></a>
            <% end %>
        </div>

    </div>
</div>

<div class="contentContainer">
    <div class="container">
        <% if vote == true %>
            <% if @story.timeLeft != false %>
                <p class="pull-right clock"><span id="clock"><%= @story.timeLeft %></span> min left</p>
            <% end %>
            <h2 class="chapterHeadline">Vote on chapter <%= round %></h2>
            <ul>
                <% @story.chapters.each do |chapter| %>
                    <% if round.to_s == chapter.round %>
                        <li class="voteChapter-container">
                            <article class="voteChapter-content" data-readmore="Read more and vote"><%= simple_format(chapter.body) %>
                            <% if signed_in? %>
                                <%= button_to 'Vote', upvote_chapter_path(chapter), method: :post, class: "pull-right btn btn-inverse" %>
                            <% else %>
                                <%= link_to "Login to vote on your favorite", login_path, class: "pull-right secondaryLink" %>
                            <% end %>
                            </article>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        <% end %>
        <% if defined?(:round) && @story.created_at > 14.hour.ago && vote == false %>
            <% if @story.timeLeft != false %>
                <p class="pull-right clock"><span id="clock"><%= @story.timeLeft %></span> min left</p>
            <% end %>
            <h2 class="chapterHeadline">New chapter</h2>
            <% if signed_in? %>
                <%= form_for([@story, @story.chapters.build]) do |f| %>
                    <input id="chapter_round" name="chapter[round]" type="hidden" value="<%= round %>">
                    <input id="chapter_author" name="chapter[author]" type="hidden" value="<%= current_user.id %>">
                    <input id="chapter_authorname" name="chapter[authorname]" type="hidden" value="<%= current_user.name %>">
                    <input id="chapter_user_id" name="chapter[user_id]" type="hidden" value="<%= current_user.id %>">
                    <div class="field"><%= f.text_area :body, placeholder: "Continue the story" %></div>
                    <div class="pull-right marginBottom"><%= f.submit %></div>
                <% end %>
            <% else %>
                <%= link_to "Login to write the next chapter", login_path, class: "pull-right btn" %>
            <% end %>
        <% end %>

        <% if @story.created_at < 14.hour.ago %>
            <h2 class="chapterHeadline textCenter">The End</h2>
            <% if friends.any? %>
                <h3>Are you wittier than your friends?</h3>
                <ul class="simpleList">
                    <% friends.each do |friend| %>
                        <li>
                            <% currentUserVote = 0 %>
                            <% current_user.chapters.each do |chapter| %>
                                <% if chapter.story == @story %>
                                <% currentUserVote = currentUserVote + chapter.votes.count %>
                                <% end %>
                            <% end %>
                            <% friendVote = 0 %>
                            <% friend.chapters.each do |chapter| %>
                                <% if chapter.story == @story %>
                                    <% friendVote = friendVote + chapter.votes.count %>
                                <% end %>
                            <% end %>
                            
                            <%= link_to(current_user) do %>
                                <%= gravatar_for current_user %> <span class="gravatarLabel">You: <%= currentUserVote %> p</span>
                            <% end %>
                            <span class="marginLeft marginRight">vs</span>
                            <%= link_to(friend) do %>
                                <%= gravatar_for friend %> <span class="gravatarLabel"><%= friend.name %>: <%= friendVote %> p</span>
                            <% end %>

                            <% if currentUserVote > friendVote %>
                                <span class="marginLeft">YES</span>
                            <% elsif currentUserVote == friendVote %>
                                <span class="marginLeft">Tie</span>
                            <% else %>
                                <span class="marginLeft">No...</span>
                            <% end %>
                        </li>
                    <% end %>
                </ul>
            <% end %>
        <% end %>

    </div>
</div>