config/routes.rb
Rails.application.routes.draw do
  resources :friendships

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :stories do
    resources :chapters
    collection do
        get 'all'
        get 'newest'
    end
  end
  resources :chapters do
    member do
      post 'upvote'
    end
  end

  root 'stories#index'

  match '/signup', to: 'users#new', via: 'get'
  match '/join', to: 'users#new', via: 'get'
  match '/login',  to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/layouts/_footer.html.erb
<footer>
    follow us on <a target="_blank" href="https://www.facebook.com/pages/Story-Wars/800681779962539" title="Follow Story Wars on Facebook"><i class="fa fa-facebook-square"></i></a> <a target="_blank" href="https://twitter.com/storywars_net" title="Follow Story Wars on Twitter"><i class="fa fa-twitter-square"></i></a>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <!-- <%= link_to "Story Wars", root_path, id: "logo", class: "logo" %> -->
        <a href="/" class="logo" title="Story Wars">
            <%= image_tag "story-wars-logotype-text-white.png" %>
        </a>
        <nav>
            <i class="mobile-menu fa fa-bars pull-right show-xs"></i>
            <ul class="nav pull-right hide-xs">
                <% if signed_in? %>
                    <%# This should be moved to a model %>
                    <% user_votes = 0 %>
                    <% current_user.stories.each do |story| %>
                        <% story.chapters.each do |chapter| %>
                            <% user_votes = user_votes + chapter.votes.count %>
                        <% end %>
                    <% end %>
                    <% current_user.chapters.each do |chapter| %>
                        <% user_votes = user_votes + chapter.votes.count %>
                    <% end %>
                    <li><%= link_to 'Write your story', new_story_path, class: "btn" %></li>
                    <li class="marginLeft avatar">
                        <%= link_to(current_user) do %>
                            <%= gravatar_for current_user %>
                            <span><%= current_user.name %> (<%= user_votes %> p)</span>
                        <% end %>
                    </li>
                    <!-- <li class="marginLeft">
                        <%= link_to "Sign out", logout_path, method: "delete", class: "btn btn-inverse" %>
                    </li> -->

                <% else %>
                    <li><%= link_to 'Write your story', new_story_path, class: "btn" %></li>
                    <li class="marginLeft last"><%= link_to "Login", login_path, class: "btn btn-inverse" %></li>
                <% end %>
            </ul>
        </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Story Wars - Writing stories together</title>
    <meta name="description" content="Collaborative and competitive writing">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag '/iphone-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '60x60' %>
    <%= favicon_link_tag '/ipad-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
    <%= favicon_link_tag '/iphone-retina-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
    <%= favicon_link_tag '/ipad-retina-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152'%>
    <!-- iOS 6 & 7 iPad (retina, portrait) -->
    <link href="/apple-touch-startup-image-1536x2008.png"
          media="(device-width: 768px) and (device-height: 1024px)
             and (orientation: portrait)
             and (-webkit-device-pixel-ratio: 2)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 & 7 iPad (retina, landscape) -->
    <link href="/apple-touch-startup-image-1496x2048.png"
          media="(device-width: 768px) and (device-height: 1024px)
             and (orientation: landscape)
             and (-webkit-device-pixel-ratio: 2)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 iPad (portrait) -->
    <link href="/apple-touch-startup-image-768x1004.png"
          media="(device-width: 768px) and (device-height: 1024px)
             and (orientation: portrait)
             and (-webkit-device-pixel-ratio: 1)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 iPad (landscape) -->
    <link href="/apple-touch-startup-image-748x1024.png"
          media="(device-width: 768px) and (device-height: 1024px)
             and (orientation: landscape)
             and (-webkit-device-pixel-ratio: 1)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 & 7 iPhone 5 -->
    <link href="/apple-touch-startup-image-640x1096.png"
          media="(device-width: 320px) and (device-height: 568px)
             and (-webkit-device-pixel-ratio: 2)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 & 7 iPhone (retina) -->
    <link href="/apple-touch-startup-image-640x920.png"
          media="(device-width: 320px) and (device-height: 480px)
             and (-webkit-device-pixel-ratio: 2)"
          rel="apple-touch-startup-image">
    <!-- iOS 6 iPhone -->
    <link href="/apple-touch-startup-image-320x460.png"
          media="(device-width: 320px) and (device-height: 480px)
             and (-webkit-device-pixel-ratio: 1)"
          rel="apple-touch-startup-image">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
</head>
<body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashes' -%>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
    
    <%= render 'layouts/footer' %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-53134362-1', 'auto');
      ga('send', 'pageview');

    </script>
</body>
</html>